### ISSUE TITLE
Compress .png picture, the background's color turns black

### ISSUE THREAD

**Issue by fuyuciel** [coobird/thumbnailator#140] opened 2019-03-07 09:09 UTC
Hello friends,
Before Compression, the background's color is transparent.
After Compression, the background's color is black.
The picture's format is png.
Thanks for yours answers.

**Comment by coobird** [comment] 2020-01-26 03:36
Without any additional details, I'm guessing this is a duplicate of #41. There's a workaround mentioned toward the end of #41.

**Comment by coobird** [comment] 2020-02-23 04:43
I'll close this as a duplicate of #41.

**Closed as completed by coobird** 2020-02-23 04:43 UTC
Labels: bug, duplicate
