### ISSUE TITLE
Thumbnailator corrupts PNG image

### ISSUE THREAD

**Issue by richiksc** [coobird/thumbnailator#144] opened 2019-05-10 15:47 UTC
## Expected behavior
Resize an image to a smaller size without greatly affecting the visual quality of it.

My source image is this: 
![git-logo](https://user-images.githubusercontent.com/8939680/57539369-f8f4b080-730f-11e9-9b12-c774259290c2.png)

and when I run it through Thumbnailator using
```java
Thumbnails.of(image)
  .size(128, 128)
  .keepAspectRatio(true)
  .outputFormat("png")
  .toFile(file);
```
I expect it to come out as a 128x128 PNG image retaining its transparent background - the file is smaller and there may be some artifacting, but no major aberrations.

## Actual behavior
The output image is this:
![logo-1 thumbnail](https://user-images.githubusercontent.com/8939680/57539713-af589580-7310-11e9-853e-5830266bfcbd.png)

The logo has lost its transparent background for a black one and there are horrible red vertical 'scanlines' running through the orange part of the logo. For some reason, this issue only happens on this image and not the 5 other images I have ran through Thumbnailator. The only difference is that this source image is an 8bit png instead of a 24bit png.

## Steps to reproduce the behavior
Run the above sample image through the provided Thumbnailator code..

## Environment
- OS vendor and version: Windows 10 version 1809
- JDK vendor and version: Oracle JDK 11.0.1 LTS
- Thumbnailator version: 0.4.8

**Comment by rntrp** [comment] 2019-05-10 16:21
Without going too much into detail, have you tried setting the image type to ARGB?
```
Thumbnails.of(image)
  .size(128, 128)
  .keepAspectRatio(true)
  .outputFormat("png")
  .imageType(ThumbnailParameter.DEFAULT_IMAGE_TYPE) // a.k.a. BufferedImage.TYPE_INT_ARGB
  .toFile(file);
```

**Comment by coobird** [comment] 2020-01-26 03:33
@richiksc As you've noticed, it happens for paletted 8-bit PNGs, and the solution posted by @rntrp  solution would work.

This is actually a duplicate of #41 which happens for index-paletted transparent PNGs.

**Closed as completed by coobird** 2020-01-26 03:33 UTC
Labels: duplicate
