### ISSUE TITLE
请问如果压缩gif才能保持gif的动画呢？

### ISSUE THREAD

**Issue by WangJincheng4869** [coobird/thumbnailator#167] opened 2020-11-16 11:34 UTC
## Expected behavior
_Please describe what you are expecting the library to perform._

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version: windows 10
- JDK 1.8
- Thumbnailator version: 0.4.11

**Comment by coobird** [comment] 2020-11-16 14:04
Thumbnailator does not support animated images (such as animated GIF) right now. Hopefully it will be supported in the future.

Closing as a duplicate of #30.

**Closed as completed by coobird** 2020-11-16 14:04 UTC
Labels: duplicate, question

**Comment by WangJincheng4869** [comment] 2020-11-17 05:44
> Thumbnailator does not support animated images (such as animated GIF) right now. Hopefully it will be supported in the future.
> 
> Closing as a duplicate of #30.

gif压缩我只想到了抽帧的方式，希望这个工具以后会支持！
