### ISSUE TITLE
Broken colors when processing PNG

### ISSUE THREAD

**Issue by pavel-klavik** [coobird/thumbnailator#165] opened 2020-10-27 17:21 UTC
## Expected behavior

The colors in hungary_broken.png are broken. They should be the same as in hungary.png.

## Actual behavior

The images:

[hungary.png](https://orgpad.com/img/CwOEdPi9tBUrwCrb1cMAKs/download?token=AIXA1cV1dHDbSdKxbYXgD1)
[hungary_broken.png](https://orgpad.com/img/CwOEdPi9tBUrwCrb1cMAKs?token=AIXA1cV1dHDbSdKxbYXgD1)

## Steps to reproduce the behavior

I am running the following code:

```java
Thumbnails/of("hungary.png")
  .scale(1)
  .outputFormat("png")
  .toFile("hungary_broken.png");
```  

## Environment

I have the following TwelveMonkeys packages included, probably unrelated to the problem:

```
[com.twelvemonkeys.imageio/imageio-jpeg "3.5"]
[com.twelvemonkeys.imageio/imageio-tiff "3.5"]
[com.twelvemonkeys.imageio/imageio-batik "3.5"]
```

- OS vendor and version: Broken on both Windows 10 (my dev environment) and Linux (our production environment).
- JDK vendor and version: OpenJDK 8.
- Thumbnailator version: 0.4.11

**Comment by coobird** [comment] 2020-10-27 17:59
For this particular case, it appears that the input image (PNG) is using an indexed color palette. It's been observed in the past that in this mode, the processed image can end up with a dithering effect.

One can avoid this dithering effect by forcing Thumbnailator to use a image mode with more colors. For example, the following will force Thumbanailator to use the 32-bit color mode (RGB with alpha), leading to a cleaner image.

```
Thumbnails/of("hungary.png")
  .scale(1)
  .imageType(BufferedImage.TYPE_INT_ARGB)
  .outputFormat("png")
  .toFile("hungary_broken.png");
```

(Note that more colors are being used, the final image may be larger than using an indexed color palette.)

**Comment by pavel-klavik** [comment] 2020-10-27 19:37
Does this setting work for all PNG images? I am using this to automatically convert images uploaded by users. I don't really care whether the generated file will be slightly larger.

**Comment by coobird** [comment] 2020-10-28 10:07
@pavel-klavik, I can't guarantee anything, but it'll likely work better than not specifying `.imageType`.

**Comment by coobird** [comment] 2020-11-15 17:14
Closing as duplicate of #26.

**Closed as completed by coobird** 2020-11-15 17:14 UTC
Labels: duplicate
