### ISSUE TITLE
Thumbnail of PNG is wrong

### ISSUE THREAD

**Issue by zhouxiangdev** [coobird/thumbnailator#135] opened 2018-10-25 03:54 UTC
## Expected behavior
_Please describe what you are expecting the library to perform._
I want to generate the thumbnail of one PNG file

## Actual behavior
_Please describe the actual behavior you are experiencing, including stack
trace and other information which would help diagnose the issue._
The source png file is this:
![3](https://user-images.githubusercontent.com/34224911/47475039-7b25f780-d84c-11e8-8819-b34ccac3dc0a.png)
The generated thumbnail is this:
![thumbnail-3-1540439433067](https://user-images.githubusercontent.com/34224911/47475051-86792300-d84c-11e8-9d9f-efa6788d2c20.png)

The color is wrong, it is supposed to be red.

## Steps to reproduce the behavior
_Please enter step-by-step instructions for reproducing the actual behavior.
Including code can be helpful in diagnosing issue, but please keep the code to
a minimal that will reproduce the behavior._
I checked the PNG file: (1200x628, 4-bit palette, non-interlaced, 98.5%).
I think it is due to 4-bit palette which is not supported. After I convert to PNG-8 or PNG-24, no issue.

## Environment
_Please provide vendor and version information for the Operating System,
JDK, and Thumbnailator. Please feel free to add any other information
which may be pertinent._

- OS vendor and version: MacOS/Ubuntu 14.04
- JDK vendor and version: Java SDK 8
- Thumbnailator version: 0.4.8

**Comment by coobird** [comment] 2020-01-26 07:36
Sorry for the late response. This appears to be a duplicate of #41.

You could try the workaround mentioned in https://github.com/coobird/thumbnailator/issues/41#issuecomment-330456553 -- basically add `.imageType(BufferedImage.TYPE_INT_ARGB)` to force Thumbnailator to process with transparencies enabled.

Hope this helps.

**Closed as completed by coobird** 2020-01-26 07:36 UTC
Labels: duplicate
