### ISSUE TITLE
Thumbnailator does not automatically rotate pictures from Samsung Galaxy S5 telephones

### ISSUE THREAD

**Issue by ReedElliott** [coobird/thumbnailator#124] opened 2017-11-18 04:16 UTC
## Expected behavior
The following code should rotate the source file based on the Exif Orientation and save in the destination file.

`Thumbnails.of(source).scale(1.0).toFile(destination);`

## Actual behavior
Destination file is not rotated.

Note: When I send my code pictures produced on other devices, the pictures are rotated properly.

I believe the following line in the getExifOrientation(..) method of the ExifUtils.java class throws an error when dealing with images from the Samsung Galaxy S5.

`IIOMetadata metadata = reader.getImageMetadata(imageIndex);`

Error: JFIF APP0 must be first marker after SOI 

## Steps to reproduce the behavior
Take a picture with Samsung Galaxy S5 and then run the above command on the file.

## Environment
- OS vendor and version:  Windows 7 Pro
- JDK vendor and version: Java 8
- Thumbnailator version: 0.4.8

**Comment by coobird** [comment] 2018-05-03 01:42
Note: Sounds similar to #108

**Comment by coobird** [comment] 2020-02-23 04:42
I'll close this as a duplicate of #108.

**Closed as completed by coobird** 2020-02-23 04:42 UTC
Labels: bug, duplicate
